// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiWywGE6lQZ1ZQq4mSx_mPDVUlT1UBv0k',
    appId: '1:181192360535:web:2f95d7f996f65e38665912',
    messagingSenderId: '181192360535',
    projectId: 'planto-app-263b6',
    authDomain: 'planto-app-263b6.firebaseapp.com',
    storageBucket: 'planto-app-263b6.appspot.com',
    measurementId: 'G-8P11Z9Y1F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvdRThMo8NjhbWUcOmgZJLGZb-XPrwV2w',
    appId: '1:181192360535:android:e290bb326e5e07a6665912',
    messagingSenderId: '181192360535',
    projectId: 'planto-app-263b6',
    storageBucket: 'planto-app-263b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1qX93NgDQ6npwahlJqyvXLuoJ00PZfAU',
    appId: '1:181192360535:ios:33cb82e4ee8ca41c665912',
    messagingSenderId: '181192360535',
    projectId: 'planto-app-263b6',
    storageBucket: 'planto-app-263b6.appspot.com',
    iosClientId: '181192360535-rtqcv7csd8nhqukehf6visrstogcgm9b.apps.googleusercontent.com',
    iosBundleId: 'com.planto.plantoFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1qX93NgDQ6npwahlJqyvXLuoJ00PZfAU',
    appId: '1:181192360535:ios:33cb82e4ee8ca41c665912',
    messagingSenderId: '181192360535',
    projectId: 'planto-app-263b6',
    storageBucket: 'planto-app-263b6.appspot.com',
    iosClientId: '181192360535-rtqcv7csd8nhqukehf6visrstogcgm9b.apps.googleusercontent.com',
    iosBundleId: 'com.planto.plantoFlutterApp',
  );
}
